ASoC-fsl_ssi: fixed compilation errors
As per commit b0a7043d5c2c ("ASoC: fsl_ssi: Caculate bit clock rate using
slot number and width"), made changes to fix the compilation errors.

sound/soc/fsl/fsl_ssi.c: In function ‘fsl_ssi_set_bclk’:
sound/soc/fsl/fsl_ssi.c:695:9: error: ‘struct fsl_ssi’ has no member named ‘bitclk_freq’
  if (ssi->bitclk_freq)
         ^~
sound/soc/fsl/fsl_ssi.c:696:13: error: ‘struct fsl_ssi’ has no member named ‘bitclk_freq’
   freq = ssi->bitclk_freq;
             ^~
sound/soc/fsl/fsl_ssi.c:688:15: warning: unused variable ‘slot_width’ [-Wunused-variable]
  unsigned int slot_width = 32;
               ^~~~~~~~~~
sound/soc/fsl/fsl_ssi.c:687:15: warning: unused variable ‘slots’ [-Wunused-variable]
  unsigned int slots = params_channels(hw_params);
               ^~~~~
scripts/Makefile.build:305: recipe for target 'sound/soc/fsl/fsl_ssi.o' failed
make[3]: *** [sound/soc/fsl/fsl_ssi.o] Error 1
scripts/Makefile.build:546: recipe for target 'sound/soc/fsl' failed
make[2]: *** [sound/soc/fsl] Error 2

Signed-off-by: Vipul Kumar <vipul_kumar@mentor.com>
Signed-off-by: Srikanth Krishnakar <Srikanth_Krishnakar@mentor.com>