MLK-22199: mxc-jpeg: Fix mxc-jpeg to build as module
The error was:
ERROR: "mxc_jpeg_enc_mode_go" [drivers/media/platform/imx8/mxc-jpeg.ko]
undefined!...(mxc_jpeg_enc_mode_go is defined in mxc-jpeg-hw.c)

Change the Makefile to build mxc-jpeg-encdec object from
these two: mxc-jpeg-hw.o mxc-jpeg.o

Signed-off-by: Mirela Rabulea <mirela.rabulea@nxp.com>
Reviewed-by: Robert Chiras <robert.chiras@nxp.com>