ASoC: fsl: fixed compilation errors
As per commit ef050bece1b5 ("ASoC: Remove platform code now everything is
componentised"), replace platform to component to fix the compilation
errors.

sound/soc/fsl/imx-pcm-dma-v2.c:218:15: error: variable ‘imx_soc_platform’ has initializer but incomplete type
 static struct snd_soc_platform_driver imx_soc_platform = {
               ^~~~~~~~~~~~~~~~~~~~~~~
sound/soc/fsl/imx-pcm-dma-v2.c:219:3: error: ‘struct snd_soc_platform_driver’ has no member named ‘ops’
  .ops  = &imx_pcm_ops,
   ^~~
sound/soc/fsl/imx-pcm-dma-v2.c:219:10: warning: excess elements in struct initializer
  .ops  = &imx_pcm_ops,
          ^
sound/soc/fsl/imx-pcm-dma-v2.c:219:10: note: (near initialization for ‘imx_soc_platform’)
sound/soc/fsl/imx-pcm-dma-v2.c:220:3: error: ‘struct snd_soc_platform_driver’ has no member named ‘pcm_new’
  .pcm_new = imx_pcm_new,
   ^~~~~~~
sound/soc/fsl/imx-pcm-dma-v2.c:220:13: warning: excess elements in struct initializer
  .pcm_new = imx_pcm_new,
             ^~~~~~~~~~~
sound/soc/fsl/imx-pcm-dma-v2.c:220:13: note: (near initialization for ‘imx_soc_platform’)
sound/soc/fsl/imx-pcm-dma-v2.c:221:3: error: ‘struct snd_soc_platform_driver’ has no member named ‘pcm_free’
  .pcm_free = imx_pcm_free_dma_buffers,
   ^~~~~~~~
sound/soc/fsl/imx-pcm-dma-v2.c:221:14: warning: excess elements in struct initializer
  .pcm_free = imx_pcm_free_dma_buffers,
              ^~~~~~~~~~~~~~~~~~~~~~~~
sound/soc/fsl/imx-pcm-dma-v2.c:221:14: note: (near initialization for ‘imx_soc_platform’)
sound/soc/fsl/imx-pcm-dma-v2.c: In function ‘imx_pcm_platform_register’:
sound/soc/fsl/imx-pcm-dma-v2.c:226:9: error: implicit declaration of function ‘devm_snd_soc_register_platform’; did you mean ‘devm_snd_soc_register_card’? [-Werror=implicit-function-declaration]
  return devm_snd_soc_register_platform(dev, &imx_soc_platform);
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
         devm_snd_soc_register_card
sound/soc/fsl/imx-pcm-dma-v2.c: At top level:
sound/soc/fsl/imx-pcm-dma-v2.c:218:39: error: storage size of ‘imx_soc_platform’ isn’t known
 static struct snd_soc_platform_driver imx_soc_platform = {
                                       ^~~~~~~~~~~~~~~~
cc1: some warnings being treated as errors
scripts/Makefile.build:305: recipe for target 'sound/soc/fsl/imx-pcm-dma-v2.o' failed
make[3]: *** [sound/soc/fsl/imx-pcm-dma-v2.o] Error 1
scripts/Makefile.build:546: recipe for target 'sound/soc/fsl' failed
make[2]: *** [sound/soc/fsl] Error 2

Signed-off-by: Vipul Kumar <vipul_kumar@mentor.com>
Signed-off-by: Srikanth Krishnakar <Srikanth_Krishnakar@mentor.com>