Revert "media: v4l2-subdev.h: remove obsolete g/s_parm"
This patch reverts commit 8180b4f4f589 ("media: v4l2-subdev.h: remove
obsolete g/s_parm") to fix the compilation errors.

drivers/media/platform/mxc/subdev/mx6s_capture.c: In function ‘mx6s_vidioc_g_parm’:
./include/media/v4l2-subdev.h:1097:42: error: ‘const struct v4l2_subdev_video_ops’ has no member named ‘g_parm’
   else if (!((sd)->ops->o && (sd)->ops->o->f))  \
                                          ^~
drivers/media/platform/mxc/subdev/mx6s_capture.c:1575:9: note: in expansion of macro ‘v4l2_subdev_call’
  return v4l2_subdev_call(sd, video, g_parm, a);
         ^~~~~~~~~~~~~~~~
./include/media/v4l2-subdev.h:1100:27: error: ‘const struct v4l2_subdev_video_ops’ has no member named ‘g_parm’
    __result = (sd)->ops->o->f((sd), ##args); \
                           ^~
drivers/media/platform/mxc/subdev/mx6s_capture.c:1575:9: note: in expansion of macro ‘v4l2_subdev_call’
  return v4l2_subdev_call(sd, video, g_parm, a);
         ^~~~~~~~~~~~~~~~
drivers/media/platform/mxc/subdev/mx6s_capture.c: In function ‘mx6s_vidioc_s_parm’:
./include/media/v4l2-subdev.h:1097:42: error: ‘const struct v4l2_subdev_video_ops’ has no member named ‘s_parm’
   else if (!((sd)->ops->o && (sd)->ops->o->f))  \
                                          ^~
drivers/media/platform/mxc/subdev/mx6s_capture.c:1584:9: note: in expansion of macro ‘v4l2_subdev_call’
  return v4l2_subdev_call(sd, video, s_parm, a);
         ^~~~~~~~~~~~~~~~
./include/media/v4l2-subdev.h:1100:27: error: ‘const struct v4l2_subdev_video_ops’ has no member named ‘s_parm’
    __result = (sd)->ops->o->f((sd), ##args); \
                           ^~
drivers/media/platform/mxc/subdev/mx6s_capture.c:1584:9: note: in expansion of macro ‘v4l2_subdev_call’
  return v4l2_subdev_call(sd, video, s_parm, a);

Signed-off-by: Vipul Kumar <vipul_kumar@mentor.com>