MLK-21076-8 rtc: imx-sc: Fix build error when CONFIG_PM_SLEEP=n
Fix below build error when CONFIG_PM_SLEEP=n:

drivers/rtc/rtc-imx-sc.c:210:9: error: ‘IMX_SC_RTC_PM_OPS’ undeclared here (not in a function)
   .pm = IMX_SC_RTC_PM_OPS,
         ^
scripts/Makefile.build:326: recipe for target 'drivers/rtc/rtc-imx-sc.o' failed
make[2]: *** [drivers/rtc/rtc-imx-sc.o] Error 1
make[2]: *** Waiting for unfinished jobs....

Signed-off-by: Anson Huang <Anson.Huang@nxp.com>
Reviewed-by: Jacky Bai <ping.bai@nxp.com>
(cherry picked from commit 0550943f8c145072580bd103ff3fdd74eb5cb807)